//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealingTalkNearestYou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counselling
    {
        public int CId { get; set; }
        public System.DateTime CDateTime { get; set; }
        public Nullable<int> CRate { get; set; }
        public string CStatus { get; set; }
        public int PsychologistPsyId { get; set; }
        public Nullable<int> PatientPatientId { get; set; }
    
        public virtual Psychologist Psychologist { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
