//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealingTalkNearestYou.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HTNYContainer1 : DbContext
    {
        public HTNYContainer1()
            : base("name=HTNYContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<Psychologist> PsychologistSet { get; set; }
        public virtual DbSet<Counselling> CounsellingSet { get; set; }
        public virtual DbSet<Patient> PatientSet { get; set; }
    }
}
