//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealingTalkNearestYou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psychologist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Psychologist()
        {
            this.Counselling = new HashSet<Counselling>();
        }
    
        public int PsyId { get; set; }
        public string PsyEmail { get; set; }
        public string PsyPassword { get; set; }
        public string PsyFirstName { get; set; }
        public string PsyLastName { get; set; }
        public string PsyGender { get; set; }
        public Nullable<System.DateTime> PsyDOB { get; set; }
        public string PsyDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Counselling> Counselling { get; set; }
    }
}
